sudo: required
language: cpp
services:
  - docker
  
env:
    - TARGET="gcc"
    - TARGET="cuda"

install:
  - docker build -t mpuccio/tracking-itsu:$TARGET -f Dockerfile.$TARGET .
 
script:
  - docker run -v $(pwd):/usr/local/tracking-itsu mpuccio/tracking-itsu:$TARGET /bin/bash test/build.sh
  
after_script:
  - docker rm -f mpuccio/tracking-itsu:$TARGET