sudo: required
language: cpp
services:
  - docker
  
env:
    - TARGET="gcc"
    - TARGET="cuda"

install:
  - docker pull glassofwhiskey/tracking-itsu:$TARGET
 
script:
  - docker run -v $(pwd):/usr/local/tracking-itsu glassofwhiskey/tracking-itsu:$TARGET /bin/bash test/build.sh
